postlight/awesome-cms

- README.md
- README.md.hbs
- scripts/generate-readme.js
Would love opinions about whether this is an improvement or not.
> Sort by Star Count

- data.toml
https://github.com/odirleiborgert/borgert-cms
> Add Borgert CMS

- data.toml
Added the PHP CMS Modx, which I personally use for client sites. This is the marketing description for the site: “MODX Revolution is the web content management platform for those that truly care about no-compromise design and exceptional user experience. It gives you complete control over your site and content, with the flexibility and scalability to adapt to your changing needs.”
> Update data.toml with Modx Revolution

- data.toml
> Add October CMS

- data.toml
> Added Alfresco, which is written in Java

- data/roadiz#roadiz.toml
- [✓] verified that the CMS I'm adding is still maintained.
- [✓] read [CONTRIBUTING.md](/CONTRIBUTING.md).
- [✓] did not generate README.md.
> Added Roadiz CMS - PHP

- data/webgradus#kms.toml
> Add KMS - RoR CMS

- data/magento#magento.toml
- [✓] verified that the CMS I'm adding is still maintained.
- [✓] read [CONTRIBUTING.md](/CONTRIBUTING.md).
- [✓] did not generate README.md.
> Magento added

- data/kunstmaan#bundlescms.toml
- data/sulu#standard.toml
> Add Sulu.io

- data/atlassian_confluence.toml
As you add closed-source CMS contributions on a case-by-case basis, let me what you think of adding Confluence.
> Add Confluence

- data/perch.toml
- data/sitecore.toml
> Add Sitecore

- data/exagonconcept.toml
- data/thegrid.toml
> Add Exagon Concept and The Grid

- .all-contributorsrc
- README.md
- README.md.hbs
- package.json
> Track Contribution with all-contributors

- data/cloudcannon.toml
> add cloudcannon

- data/kentico.toml
- [X ] verified that the CMS I'm adding is still maintained.
- [ X] read [CONTRIBUTING.md](/CONTRIBUTING.md).
- [ X] did not generate README.md.
> Create new file to add Kentico CMS

- data/zesty.io.toml
> Add Zesty.io

- data/webgradus#kms.toml
> Update KMS - add website URL

- data/netlify#netlify-cms.toml
> Add website to Netlify CMS

- data/thomas4019#expressa.toml
> Add Expressa to Javascript

- data/buttercms.toml
> adds buttercms

- data/craft cms.toml
> Update craft cms.toml

- data/storyblok.toml
> adds Storyblok - API based CMS for components.

- data/gentics#mesh.toml
> Add gentics mesh

- data/textpattern#textpattern.toml
> Textpattern website is now HTTPS

- data/forestry.toml
> Added Forestry to the list

- data/typicms#base.toml
> TypiCMS Added.

- kalikocms#kalikocms.core.toml
- [Y] verified that the CMS I'm adding is still maintained.
- [Y] read [CONTRIBUTING.md](/CONTRIBUTING.md).
- [Y] did not generate README.md.
> Adding Kaliko CMS

- data/platformus#platformus.toml
- [Y] verified that the CMS I'm adding is still maintained.
- [Y] read [CONTRIBUTING.md](/CONTRIBUTING.md).
- [Y] did not generate README.md.
> Added Platformus CMS

- data/etewiah#property_web_builder.toml
> Please add Property Web Builder

- data/graphcms.toml
> Adding GraphCMS to closed source

- data/flamelink.toml
> Add Flamelink

- squidex#repo.toml
> Added Squidex CMS to the list (I am the main contributor)

- org#repo.toml
> Added WonderCMS to your list (I'm the main contributor)

- data/punkave#apostrophe.toml
> Add url to Apostrophe

- data/ketchuphq#ketchup.toml
> Add Ketchup

- data/quintype.toml
> Add Quintype CMS

- data/unite-cms#unite-cms.toml
> Add unite cms

- superdesk#superdesk.toml
> Add Superdesk

- data/awesomecmscore#awesomecmscore.toml
> add awesome cms core

- data/takeshape.toml
> add TakeShape

- gatsbyjs#gatsby.toml
Adding Gatsby.js
Gatsby is a blazing fast modern site generator for React.
> Adding Gatsby.js

- data/birkir#prime.toml
> Added Prime CMS

- data/sanity-io#sanity.toml
> Add Sanity.io

- data/punkave#apostrophe.toml
- [ x ] verified that the CMS I'm adding is still maintained.
- [ x ] read [CONTRIBUTING.md](https://github.com/postlight/awesome-cms/blob/master/CONTRIBUTING.md).
- [ x ] did not generate README.md.
Just updating the description to one based on the current description in the repo. Thanks!
> updated description to that which comes with current version

- data/elepy#elepy.toml
> Elepy, the Headless Content Management Framework.

- data/factor#factor.toml
> Add Factor JS

- data/kentico-ems.toml
- data/kentico-kontent.toml
Renamed Kentico to Kentico EMS and added Kentico Kontent.
Note:
If you are interested, I am maintaining the [Kentico Github organization](https://github.com/Kentico) as well. There is no source code of Kentico products but contains SDKs, sample applications and useful tools for its products.
> Adjust Kentico CMSs

- README.md
- README.md.hbs
- data/saigonsoftware#awesomecmscore.toml
> feat: badgen badges!

- data/frontaid-cms.toml
> Add FrontAid CMS

- data/azuriom#azuriom.toml
> Add Azuriom

- data/payloadcms#payloadcms.toml
> Add Payload CMS

- data/torchbox#wagtail.toml
> The Wagtail repo has moved to its own organisation

- data/refinery#refinerycms.toml
> Update Refinery's Rails version in its description

- data/blogody.toml
> add blogody

- data/spinal.toml
Add [Spinal](https://spinalcms.com/) as a closed-source CMS.
> Added https://spinalcms.com/ as a closed-source CMS

- wintercms#winter.toml
> Add Winter CMS

- data/contember#engine.toml
Hi @mutewinter,
I would love to add Contember CMS to your list. Would you be kind enough to do a review?
Thank you in advance.
> Add Contember to list

- atomic#atomic-server.toml
Hi there! I'd like to add my open source CMS project to this list, which is in Rust (which means: new category?).
> Add Atomic Server

- data/apostrophecms#apostrophe.toml
> chore: update org for Apostrophe

- data/microfeed#microfeed.toml
> Add microfeed to list

- data/saleor.toml
- [ x] verified that the CMS I'm adding is still maintained.
- [x ] read [CONTRIBUTING.md](https://github.com/postlight/awesome-cms/blob/master/CONTRIBUTING.md).
- [x ] did not generate README.md.
> Add Saleor
